use serde::{Deserialize, Serialize};

use super::EngineKind;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EnginePreset {
    pub id: String,
    pub label: String,
    pub engine: EngineKind,
    pub hf_repo: String,
    pub model_size_b: f32,
    pub default_context: usize,
    pub default_port: u16,
    pub recommended_gpu: String,
    pub default_quantization: Option<String>,
    pub default_tp: usize,
    pub enable_mtp: bool,
    pub enable_vision: bool,
    pub description: String,
}

pub fn get_preset_templates() -> Vec<EnginePreset> {
    vec![
        EnginePreset {
            id: "qwen-3.5-9b-llamacpp-128k".to_string(),
            label: "Qwen 3.5 9B (llama.cpp 128k Local GGUF)".to_string(),
            engine: EngineKind::LlamaCpp,
            hf_repo: "/models/Qwen3.5-9B-UD-Q4_K_XL.gguf".to_string(),
            model_size_b: 9.0,
            default_context: 131072,
            default_port: 8080,
            recommended_gpu: "1x 16GB VRAM (AMD RX 7000 / RTX 4080)".to_string(),
            default_quantization: Some("q4".to_string()),
            default_tp: 1,
            enable_mtp: false,
            enable_vision: true,
            description: "High-capacity 128k context model running via llama.cpp GGUF. Uses ~9.3 GB total VRAM on 16 GB GPUs with Q8 KV cache and native vision support.".to_string(),
        },
        EnginePreset {
            id: "qwen-3.8-27b-vllm".to_string(),
            label: "Qwen 3.8 27B (cyankiwi AWQ 4-bit / 64k MTP)".to_string(),
            engine: EngineKind::Vllm,
            hf_repo: "cyankiwi/Qwen3.8-27B-AWQ-INT4".to_string(),
            model_size_b: 27.0,
            default_context: 65536,
            default_port: 8000,
            recommended_gpu: "1x 24GB VRAM (RTX 3090/4090/A10G) or 2x 16GB (TP=2)".to_string(),
            default_quantization: Some("awq".to_string()),
            default_tp: 1,
            enable_mtp: true,
            enable_vision: true,
            description: "High-intelligence frontier model with 64k context window, multi-token prediction (MTP) enabled, multimodal image inputs, and AWQ quantization targeted for 24GB GPUs.".to_string(),
        },
        EnginePreset {
            id: "qwen-3.5-9b-vllm".to_string(),
            label: "Qwen 3.5 9B (QuantTrio AWQ 4-bit / 16k Fast)".to_string(),
            engine: EngineKind::Vllm,
            hf_repo: "QuantTrio/Qwen3.5-9B-AWQ".to_string(),
            model_size_b: 9.0,
            default_context: 16384,
            default_port: 8000,
            recommended_gpu: "1x 12GB - 16GB VRAM (Navi 32/33/RX 7000/RTX 4070/4080)".to_string(),
            default_quantization: Some("awq".to_string()),
            default_tp: 1,
            enable_mtp: false,
            enable_vision: true,
            description: "High-speed agentic model with 16k context, FP8 KV cache, native image understanding, optimized for 12GB-16GB GPUs without VRAM overflow.".to_string(),
        },
        EnginePreset {
            id: "gemma-4-12b-vllm".to_string(),
            label: "Gemma 4 12B Instruct (cyankiwi AWQ 4-bit / 64k MTP)".to_string(),
            engine: EngineKind::Vllm,
            hf_repo: "cyankiwi/gemma-4-12B-it-AWQ-INT4".to_string(),
            model_size_b: 12.0,
            default_context: 65536,
            default_port: 8000,
            recommended_gpu: "1x 16GB VRAM (RTX 4080, T4, V100)".to_string(),
            default_quantization: Some("awq".to_string()),
            default_tp: 1,
            enable_mtp: true,
            enable_vision: true,
            description: "Google DeepMind open architecture with 64k context window, multi-token prediction enabled, multimodal vision encoding, and 4-bit AWQ targeting 16GB VRAM.".to_string(),
        },
        EnginePreset {
            id: "gemma-4-31b-vllm".to_string(),
            label: "Gemma 4 31B Instruct (Google Open Weights / 64k MTP)".to_string(),
            engine: EngineKind::Vllm,
            hf_repo: "google/gemma-4-31B-it".to_string(),
            model_size_b: 31.0,
            default_context: 65536,
            default_port: 8000,
            recommended_gpu: "1x 24GB (AWQ) or 2x 24GB (TP=2, FP8)".to_string(),
            default_quantization: Some("awq".to_string()),
            default_tp: 1,
            enable_mtp: true,
            enable_vision: true,
            description: "Flagship DeepMind open-weights model with 64k context window, MTP multi-token prediction, multimodal vision perception, and AWQ quantization for 24GB GPUs.".to_string(),
        },
        EnginePreset {
            id: "muse-glimmer-vision".to_string(),
            label: "Muse Glimmer 30B (Vision & Image Native / 64k MTP)".to_string(),
            engine: EngineKind::Vllm,
            hf_repo: "meta-models/Muse-Glimmer-30B".to_string(),
            model_size_b: 30.0,
            default_context: 65536,
            default_port: 8000,
            recommended_gpu: "1x 24GB or 2x 16GB VRAM".to_string(),
            default_quantization: Some("awq".to_string()),
            default_tp: 1,
            enable_mtp: true,
            enable_vision: true,
            description: "Native vision-language generative multimodal model with direct image inputs, 64k context, MTP multi-token prediction, and optimized vision encoder pipeline.".to_string(),
        },
        EnginePreset {
            id: "qwen-3.5-9b-gguf".to_string(),
            label: "Qwen 3.5 9B GGUF (llama.cpp Server / 64k)".to_string(),
            engine: EngineKind::LlamaCpp,
            hf_repo: "unsloth/Qwen3.5-9B-GGUF".to_string(),
            model_size_b: 9.0,
            default_context: 65536,
            default_port: 8080,
            recommended_gpu: "CPU or modest GPU (8GB-12GB VRAM)".to_string(),
            default_quantization: Some("k-quants".to_string()),
            default_tp: 1,
            enable_mtp: true,
            enable_vision: true,
            description: "Optimized GGUF quantization (Q4_K_M) running in llama.cpp with 64k context window, partial/full GPU offloading, and image input support.".to_string(),
        },
        EnginePreset {
            id: "ollama-qwen-3.5".to_string(),
            label: "Ollama Inference Engine Server (Qwen 3.5 9B)".to_string(),
            engine: EngineKind::Ollama,
            hf_repo: "qwen3.5:9b".to_string(),
            model_size_b: 9.0,
            default_context: 65536,
            default_port: 11434,
            recommended_gpu: "Any GPU / Apple Silicon / CPU".to_string(),
            default_quantization: None,
            default_tp: 1,
            enable_mtp: true,
            enable_vision: true,
            description: "Standard local Ollama daemon container running latest Qwen 3.5 9B with 64k context, accessible via OpenAI-compatible endpoints.".to_string(),
        },
    ]
}
